### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by plehegar** [w3c/conneg-prof-testing#1]
Following
  https://github.com/github/renaming

we should rename the master branch to main.

I'd like +1 from @nicholascar @rob-metalinkage before doing so.

**Comment by nicholascar** [comment]
+1

**Comment by plehegar** [comment]
Switch done. I recommend re-cloning the repo locally if you have a copy (but make sure you have no pending changes locally first).

If you do have local changes, you'll need to follow item 2 in https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0017.html
